--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DaisukeDaisuke/AwaitFormOptions
build-by-default: true
branches:
- main
projects:
  type: "library"
  AwaitFormOptions:
    path: ""
...
